project_name: cors-reverse-proxy
env:
  - GO111MODULE=on
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: cors-reverse-proxy
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
